
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    macos:
      xcode: 13.0.0
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run: cargo --version
      - run: cargo build --release
  release:
    requires:
            - build
    steps:
      - run: find .

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-release:
    jobs:
      - build
