name: Release Binaries

on:
  workflow_dispatch:  
  push:
    tags:
      - "*-alpha-DISABLED"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Prepare Variables
        run: |
          app_version=$(grep version Cargo.toml|cut -d"\"" -f2|head -n 1)
          echo "APP_VERSION=${app_version}" >> $GITHUB_ENV

      - name: Create DRAFT Release
        run: |
          gh release create ${{ env.APP_VERSION }} --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Summary
        run: |
          echo "| APP_VERSION  | ${{ env.APP_VERSION }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :----------- | ---------------------: |" >> $GITHUB_STEP_SUMMARY

  release_binaries:
    name: Release Binaries
    needs: create_release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Prepare Variables
        run: |
          app_version=$(grep version Cargo.toml|cut -d"\"" -f2|head -n 1)
          echo "APP_VERSION=${app_version}" >> $GITHUB_ENV

      - name: Install Stable rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Create Distribution
        run: |
          dist_dir="${{ runner.temp }}/dist/omt-linux"
          mkdir -p ${dist_dir}
          cp target/release/omt-asset ${dist_dir}
          cp target/release/omt-atlas ${dist_dir}
          cp target/release/omt-font ${dist_dir}
          cp target/release/omt-packer ${dist_dir}
          cp target/release/omt-script ${dist_dir}
          cp target/release/omt-shader ${dist_dir}
          cp target/release/omt-soundbank ${dist_dir}
          cp target/release/omt-xcassets ${dist_dir}
          cd ${dist_dir}
          pwd
          ls
          cd ..
          pwd
          ls -l
          ls -l omt-linux/*
          tar czf omt-linux-${{ env.APP_VERSION }}.tgz omt-linux/*
          ls -l

      - name: Upload to Release
        run: |
          dist_dir="${{ runner.temp }}/dist/omt-linux"
          mkdir -p ${dist_dir}
          cd ..
          ls -l *.tgz
          gh release upload ${{ env.APP_VERSION }} omt-linux-${{ env.APP_VERSION }}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Summary
        run: |
          echo "| APP_VERSION  | ${{ env.APP_VERSION }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :----------- | ---------------------: |" >> $GITHUB_STEP_SUMMARY

  release_release:
    name: Release Release
    needs: release_binaries
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Prepare Variables
        run: |
          app_version=$(grep version Cargo.toml|cut -d"\"" -f2|head -n 1)
          echo "APP_VERSION=${app_version}" >> $GITHUB_ENV

      - name: Create DRAFT Release
        run: |
          gh release edit ${{ env.APP_VERSION }} --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Summary
        run: |
          echo "| APP_VERSION  | ${{ env.APP_VERSION }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :----------- | ---------------------: |" >> $GITHUB_STEP_SUMMARY
